### ISSUE TITLE
add guidance on the reserve doi for README issue

### ISSUE THREAD

**Issue by gergelyattilakiss** [REStud/data-editor#12]
Jonathan Zinman raised the question how to do this. Let me reply him and then write the part for the guidance.

**Comment by gergelyattilakiss** [comment]
what about something like this: 

# Finale version
The editor accepted the latest version of the replication package? You should then update the readme to include the appropriate doi. But... wait? won't the doi change when I update the readme?

That is right. After the replication package is approved you need to upload a new verion under the same record. And while uploading you have to reserve first a doi then write that doi into the readme, zip the package and finally upload to zenodo in the same workflow where you reserved the doi. You can find a screenshot below showing where you can find the reserve doi button while uploading.

I know it is somewhat too pushy just a suggestion.

**Comment by korenmiklos** [comment]
Will be done in #13
