### ISSUE TITLE
Update the submission part

### ISSUE THREAD

**Issue by gergelyattilakiss** [REStud/data-editor#19]
Since zenodo updated we did not refresh the after section, it cause some confusion in case of 31695.

**Comment by korenmiklos** [comment]
Michal, you will need to edit https://github.com/REStud/data-editor/blob/master/after.md to match the new Zenodo UI. Please save screenshots too..

Do this on a separate branch and create a PR.

**Comment by michal-reczek** [comment]
I did all that and created a pull request.

**Comment by gergelyattilakiss** [comment]
Finally, I could run the jekyll compilation the screenshots look good.
